---
title: "K Means Clustering"
author: "Christopher C. Beville"
date: "March 10, 2019"
output: html_document
---

```{r}
## Load the libraries
library(tidyverse)
library(cluster)
```

```{r}
## Load the data
data <- read_csv('Mall_Customers.csv')
glimpse(data)
```

```{r}
## Discard the columns that we will not be using
X <- data[4:5]

## Change the column names so they are easier to work with later
colnames(X) <- c('Annual_Income', 'Spending_Score')  
```

```{r}
## Set the seed for reproducibility
set.seed(6)

## Analyse for the optimal number of clusters
wcss <- vector()
for (i in 1:10) wcss[i] <- sum(kmeans(X, i)$withinss)
plot(1:10, wcss, type = 'b', 
     main = paste('Clusters of Customers'), 
     xlab = 'Number of Clusters', ylab = 'WCSS')
```

```{r}
## Create K-means model
set.seed(29)
clusterModel <- kmeans(X, centers = 5, iter.max = 300, nstart = 10)
glimpse(clusterModel)
```

```{r}
## Visualize the clusters
X %>%
ggplot(aes(x = Annual_Income, y = Spending_Score, 
           color = as.factor(clusterModel$cluster))) +
  geom_point() +
  ggtitle('Cluster of Clients') +
  labs(color = 'Cluster')
```

```{r}
## Same visualization using clusplot
clusplot(X,
         clusterModel$cluster,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste('Clusters of Clients'),
         xlab = 'Annual Income',
         ylab = 'Spending Score')
```

     







  



