---
title: "AdventureWorks With Azure Connection"
subtitle: "Tidy Data, Visualizations w/ ggplot2, Apriori Basket Analysis
author: "Chris Beville"
date: "14 10 2019"
output: html_document
---


```{r}
## Load Libraries
library(tidyverse)
library(RODBC)
library(ggrepel)
library(arules)
library(tm)
```


```{r}
## Create Azure Connection
server <- 'cbevillemain.database.windows.net'
user <- 'chrisbeville'
password <- 'RichBitch@33' 
database <- 'AdventureWorks2016-Standard'
driver <- 'SQL Server'
connectionString <- paste0(
                        'Driver=', driver,
                        ';Server=', server,
                        ';Database=', database,
                        ';Uid=', user,
                        ';Pwd=', password)
```
                        

```{r}
## Queries to load data into environment
sqlQuery2 <- "SELECT	A.SalesOrderID, A.OrderQty, A.ProductID, E.Name, A.UnitPrice, A.LineTotal, A.ModifiedDate,
		                B.OrderDate, B.CustomerID, B.TerritoryID, B.SubTotal, 
		                C.StoreID,  
		                D.Name
              FROM [Sales].[SalesOrderDetail] A
              JOIN [Sales].[SalesOrderHeader] B
              ON A.SalesOrderID = B.SalesOrderID
              JOIN Sales.Customer C
              ON B.CustomerID = C.CustomerID
              JOIN Sales.Store D
              ON C.StoreID = D.BusinessEntityID
              JOIN Production.Product E
              ON A.ProductID = E.ProductID"
```


```{r}
## Create Connection with Server
conn <- odbcDriverConnect(connectionString)

## Create data frame with the prescribed query and using the above connection
df2 <- sqlQuery(conn, sqlQuery2)

## Close the connection
close(conn) 
```


```{r}
## Have a 'glimpse' at our data
glimpse(df2)

## Statistical Overview of our data
summary(df2)
```

  
```{r}
## Inner Join two data frames showing total Average Unit Price by month.
x <- df2 %>%
  select(ModifiedDate, LineTotal) %>%
  mutate(SalesDate = format(lubridate::ymd(ModifiedDate), '%m')) %>%
  group_by(SalesDate) %>%
  summarize(TotalRevenue = sum(LineTotal)) 
  
y <- df2 %>%
  select(ModifiedDate, OrderQty) %>%
  mutate(SalesDate = format(lubridate::ymd(ModifiedDate), '%m')) %>%
  group_by(SalesDate) %>%
  summarize(TotalSalesQty = sum(OrderQty))
  
AUP <- inner_join(x, y) %>%
  mutate(AvgUnitPrice = TotalRevenue / TotalSalesQty)
```
  

```{r}
## Total Monthy Revenue  
AUP %>%
  ggplot(aes(x = SalesDate, y = TotalSalesQty)) +
  geom_line(aes(group = 1), color = 'blue') +
  geom_point(color = 'black') +
  geom_text(aes(label = paste('$', format(round(TotalRevenue, 2), big.mark = ",", scientific = FALSE)), vjust = -1)) +
  labs(title = 'Change In Total Monthly Revenue',
        x = 'Month',
        y = 'Total Revenue')
```
  

```{r}
## Monthly Change in Average Unit Price 
AUP %>%
  ggplot(aes(x = SalesDate, y = AvgUnitPrice)) +
  geom_line(aes(group = 1), color = 'blue') +
  geom_point(color = 'black') +
  geom_text(aes(label = paste('$', format(round(AvgUnitPrice, 2), big.mark = ",", scientific = FALSE)), vjust = -1)) +
  labs(title = 'Average Unit Price Change Month Over Month',
        x = 'Month',
        y = 'Average Unit Price')
```


```{r}
## Monthly Change in Total Units Sold
AUP %>%
  ggplot(aes(x = SalesDate, y = TotalSalesQty)) +
  geom_line(aes(group = 1), color = 'blue') +
  geom_point(color = 'black') +
  geom_text(aes(label = TotalSalesQty, vjust = -1)) +
  labs(title = 'Change In Units Sold Month Over Month',
        x = 'Month',
        y = 'Units Sold')
```

        
```{r}
## Top 2 Sales Items MOM
df2 %>%
  mutate(SalesDate = format(lubridate::ymd(ModifiedDate), '%m')) %>%
  group_by(SalesDate) %>%
  select(SalesDate, ProductID, Name, OrderQty) %>%
  top_n(2, OrderQty) %>%
  ggplot(aes(x = SalesDate, y = OrderQty)) +
  geom_point(color = 'blue', size = 3) +
  labs(title = 'Top Items Sold Each Month',
        x = 'Month',
        y = 'Quantity Ordered') +
  geom_label_repel(aes(label = Name), size = 3, box.padding = .5, point.padding = .25) +
  theme(panel.grid.major = element_line(size = 3))
```


```{r}
## Top 2 Sales Items MOM with Month Abbreviations on the X axis.   
df2 %>%
   mutate(SalesDate = format(lubridate::ymd(ModifiedDate), '%m')) %>%
   mutate(SalesMonth = case_when(SalesDate == '01' ~ 'Jan',
                    SalesDate == '02' ~ 'Feb',
                    SalesDate == '03' ~ 'Mar',
                    SalesDate == '04' ~ 'Apr',
                    SalesDate == '05' ~ 'May',
                    SalesDate == '06' ~ 'June',
                    SalesDate == '07' ~ 'July',
                    SalesDate == '08' ~ 'Aug',
                    SalesDate == '09' ~ 'Sep',
                    SalesDate == '10' ~ 'Oct',
                    SalesDate == '11' ~ 'Nov',
                    SalesDate == '12' ~ 'Dec')) %>%
  group_by(SalesMonth) %>%
  select(SalesMonth, SalesDate, ProductID, Name, OrderQty) %>%
  top_n(2, OrderQty) %>%
  ggplot(aes(x = fct_relevel(SalesMonth, c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')), 
             y = OrderQty)) +
  geom_point(color = 'blue', size = 3) +
  labs(title = 'Top 2 Items Sold Each Month',
        x = 'Month',
        y = 'Quantity Ordered') +
  geom_label_repel(aes(label = Name), size = 3, box.padding = .5, point.padding = .25) +
  theme(panel.grid.major = element_line(size = 3))
```
  

```{r}
## Total Units Sold of Each Product
inner_join(df2 %>%
  group_by(ProductID) %>%
  count() %>%
  arrange(desc(n)),
  df2 %>%
  distinct(ProductID, Name)) %>%
select(ProductID, Name, n) %>%
rename(TotalUnitsSold = n) %>%
View()
```


```{r}
## Use the Apriori Algorithm to Find Items Frequently Bought Together.
## Coerce data frame into appropriate format
AW_Sales <- df2 %>%
                select(SalesOrderID, StoreID, OrderDate, Name) %>%
                separate(Name, c("ProductName", "Desc"), sep = ",") %>%
                select(-Desc)

glimpse(AW_Sales)
```


```{r}
## Create "Basket" for Algorithm
basket <- plyr::ddply(AW_Sales, c("SalesOrderID", "StoreID", "OrderDate"), function(df1)paste(df1$ProductName, collapse = ","))

View(basket)
```

 
```{r}
## Discard the columns that we will not be needing
basket <- basket %>%
            select(V1) %>%
            rename(Items = V1)
```


```{r}
## Write our data frame to .csv
write.csv(basket, "C:/Users/CHBE/Documents/AW_Sales_Basket.csv", quote = FALSE, row.names= FALSE)
```


```{r}
## Create Transactions data for algorithm
transactions <- read.transactions("AW_Sales_Basket.csv", format = "basket", sep = ",")
```


```{r}
## Run apriori algorithm on transaction data
rules <- apriori(transactions, parameter = list(supp = 0.01, conf = 0.6, minlen = 1, maxlen = 6))
```


```{r}
## Convert output to data frame and view results
AW_Sales_Rules <- as(rules[1:5000], "data.frame")
View(AW_Sales_Rules[1:1000,])
```



